apiVersion: v1
kind: Namespace
metadata:
  name: ui
  labels:
    app.kubernetes.io/owner: retail-store-sample
---
apiVersion: v1
kind: Namespace
metadata:
  name: catalog
  labels:
    app.kubernetes.io/owner: retail-store-sample
---
apiVersion: v1
kind: Namespace
metadata:
  name: carts
  labels:
    app.kubernetes.io/owner: retail-store-sample
---
apiVersion: v1
kind: Namespace
metadata:
  name: orders
  labels:
    app.kubernetes.io/owner: retail-store-sample
---
apiVersion: v1
kind: Namespace
metadata:
  name: checkout
  labels:
    app.kubernetes.io/owner: retail-store-sample
